### ISSUE TITLE
xgb produces non-recoverable panic when X server is closed

### ISSUE THREAD

**Issue by extemporalgenome** [BurntSushi/xgb#25]
When an X server closes, normally or otherwise, xgb panics within a goroutine it has itself created, making the panic non-recoverable. As per Go convention, panics should really only be exposed/visible to the calling program if the programmer has made a mistake. In this case, the panic is preventing me from cleaning up a unix domain socket (by design, the kernel doesn't/won't ever do that for us), and in my case, I do need to do useful work after the X server is gone.

Stack trace follows:

XGB: xgb.go:371: A read error is unrecoverable.
panic: EOF

goroutine 9 [running]:
runtime.panic(0x58e2a0, 0xc208028060)
    /home/kevin/go/src/pkg/runtime/panic.c:278 +0xf8
github.com/BurntSushi/xgb.(*Conn).readResponses(0xc208078000)
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:372 +0x366
created by github.com/BurntSushi/xgb.NewConnDisplay
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:113 +0x20b

goroutine 1 [select]:
main.Server(0xc20800a080, 0x11)
    /home/kevin/src/github.com/extemporalgenome/xrs/main.go:142 +0xb55
main.main()
    /home/kevin/src/github.com/extemporalgenome/xrs/main.go:85 +0x57b

goroutine 4 [finalizer wait]:
runtime.park(0x421620, 0x6d6f10, 0x6d53da)
    /home/kevin/go/src/pkg/runtime/proc.c:1406 +0x9d
runtime.parkunlock(0x6d6f10, 0x6d53da)
    /home/kevin/go/src/pkg/runtime/proc.c:1422 +0x3e
runfinq()
    /home/kevin/go/src/pkg/runtime/mgc0.c:1659 +0xd8
runtime.goexit()
    /home/kevin/go/src/pkg/runtime/proc.c:1475

goroutine 5 [syscall]:
os/signal.loop()
    /home/kevin/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /home/kevin/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /home/kevin/go/src/pkg/runtime/proc.c:1475

goroutine 6 [chan send]:
github.com/BurntSushi/xgb.(*Conn).generateXIds(0xc208078000)
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:236 +0x1b5
created by github.com/BurntSushi/xgb.NewConnDisplay
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:110 +0x1c3

goroutine 7 [chan send]:
github.com/BurntSushi/xgb.(*Conn).generateSeqIds(0xc208078000)
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:258 +0x71
created by github.com/BurntSushi/xgb.NewConnDisplay
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:111 +0x1db

goroutine 8 [chan receive]:
github.com/BurntSushi/xgb.(*Conn).sendRequests(0xc208078000)
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:303 +0x7a
created by github.com/BurntSushi/xgb.NewConnDisplay
    /home/kevin/src/github.com/BurntSushi/xgb/xgb.go:112 +0x1f3

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7f941c410b38, 0x72, 0x0)
    /home/kevin/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(_pollDesc).Wait(0xc20807a1b0, 0x72, 0x0, 0x0)
    /home/kevin/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(_pollDesc).WaitRead(0xc20807a1b0, 0x0, 0x0)
    /home/kevin/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(_netFD).accept(0xc20807a150, 0x0, 0x7f941c40f940, 0xb)
    /home/kevin/go/src/pkg/net/fd_unix.go:419 +0x344
net.(_UnixListener).AcceptUnix(0xc20800a380, 0xc208097f60, 0x0, 0x0)
    /home/kevin/go/src/pkg/net/unixsock_posix.go:282 +0x51
net.(*UnixListener).Accept(0xc20800a380, 0x0, 0x0, 0x0, 0x0)
    /home/kevin/go/src/pkg/net/unixsock_posix.go:293 +0x4b
main.func·005()
    /home/kevin/src/github.com/extemporalgenome/xrs/main.go:116 +0x4d
created by main.Server
    /home/kevin/src/github.com/extemporalgenome/xrs/main.go:131 +0x609

**Comment by kishorv06** [comment]
For anyone who wants to exit application gracefully when the window is closed, here is the code for you. Being a newbie in golang and due to lack for noob friendly documentation, It took me a few hours to get this sorted.

```go
wmDeleteAtomCookie := xproto.InternAtom(X, false, uint16(len("WM_DELETE_WINDOW")), "WM_DELETE_WINDOW")
wmDeleteAtom, _ := wmDeleteAtomCookie.Reply()
wmProtocolsCookie := xproto.InternAtom(X, false, uint16(len("WM_PROTOCOLS")), "WM_PROTOCOLS")
wmProtocols, _ := wmProtocolsCookie.Reply()
xproto.ChangeProperty(X, xproto.PropModeReplace, wid, wmProtocols.Atom, xproto.AtomAtom, byte(32), uint32(1), (*[4]byte)(unsafe.Pointer(&wmDeleteAtom.Atom))[:])

// In your WaitForEvent or PollForEvent loop
if event, ok := ev.(xproto.ClientMessageEvent); ok && event.Data.Data32[0] == uint32(wmDeleteAtom.Atom) {
	// write your exit logic here. Window will not be closed automatically.
}
```

Reference: https://stackoverflow.com/a/1186544

**Comment by jezek** [comment]
I'm glad you sorted it out.
Could you write an example, so next time someone would have a easier time to figure out? Something like https://github.com/BurntSushi/xgb/blob/master/examples/create-window/main.go

PS: Why did you write this in this issue? Does it fix the issue? (I've tackled with this kind of panics in PR #44)
Note: Some time ago, I've been trying to figure out graceful exit handling, which resulted in a [xgb wrapper](https://github.com/jezek/xgo), which I use in my side projects. I've done an [graceful exit handling example too](https://github.com/jezek/xgo/blob/master/examples/createAndHandleWindow/main.go).

**Comment by kishorviswanathan** [comment]
@jezek Sure, I will write an example. I already saw your `xgb wrapper`. But by that time, I have already implemented my requirements. My only requirement was to create a window and embedded `mplayer` in it. Then grab all the inputs sent to the window. So the `xgb` module was already enough for me.

However, The reason why I posted it here is that, like @extemporalgenome mentioned, I also wanted to do some cleanup tasks ( like killing the `mplayer` process )  when the window was closed. But that non-recoverable panic was ignoring my recover attempts. So I had to find a way to handle exit gracefully and then close the window. `xgb` could be panicking even now, but the good thing is, it is no longer affecting my application logic and there is nothing getting printed on the console.

**Comment by jezek** [comment]
@kishorv06 The panic was not recoverable, cause it was thrown in go routine, IIRC.
You should try [my fork](https://github.com/jezek/xgb), the panics should have been fixed there.

Also you can make the PR for the example there. This repo is [newly deprecated](https://github.com/BurntSushi/xgb/blob/master/README#L1-L3). Thank you.
