### ISSUE TITLE
Trying to get notified when a window gets closed

### ISSUE THREAD

**Issue by muesli** [BurntSushi/xgb#47]
I'm trying to receive DestroyNotify events, to detect when a specific window has been closed. If I understand the Xlib docs correctly, I need to change the window attributes and add xproto.EventMaskStructureNotify to receive those notifications.

However I just can't seem to work it out. Could you provide an example for that scenario?

**Comment by BurntSushi** [comment]
Please show your code in the form of a compilable program.

**Comment by muesli** [comment]
What I'm trying boils down to this. Obviously you'd have to change the window id to something that's actually valid on your system.

```
package main

import (
	"fmt"

	"github.com/BurntSushi/xgb"
	"github.com/BurntSushi/xgb/xproto"
)

var (
	winId = xproto.Window(12345678)
)

func main() {
	conn, err := xgb.NewConn()
	if err != nil {
		panic(err)
	}

	xproto.ChangeWindowAttributes(conn, winId, xproto.CwEventMask,
		[]uint32{xproto.EventMaskStructureNotify})

	for {
		ev, err := conn.WaitForEvent()
		if err != nil {
			panic(err)
		}

		switch e := ev.(type) {
		case xproto.DestroyNotifyEvent:
			fmt.Printf("Destroyed: %+v\n", e)
		}
	}
}
```

**Comment by BurntSushi** [comment]
Your example works just fine. I ran `xwininfo` and clicked on a window I had open to get its ID. Then I put the ID into your program. I ran the program and then closed the window, and I got this output:

```
Destroyed: DestroyNotify {Sequence: 1, Event: 44040195, Window: 44040195}
```

**Comment by muesli** [comment]
@BurntSushi Thanks for the prompt feedback. The example is indeed fine, and it turned out to be a problem only when the window attributes had been changed before. I'm having a hard time making sense of the xlib documentation here, but from what I can tell, this is not a problem of this package one way or another. Closing as such.
