### ISSUE TITLE
getting screen rgba value.

### ISSUE THREAD

**Issue by ghost** [BurntSushi/xgb#58]
can you provide some documentation on using the GetImage function. I want to be able to capture the state of the screen and get a rgba value.

**Comment by ghost** [comment]
got it, code example for anyone else that needs help
```go
screen := xproto.Setup(X).DefaultScreen(X)

	imgCookie := xproto.GetImage(X, xproto.ImageFormatZPixmap, xproto.Drawable(screen.Root), 0, 0, screen.WidthInPixels, screen.HeightInPixels, 0xffffffff)
	img, err := imgCookie.Reply()
	if err != nil {
		fmt.Println(err)
		return
}
```

**Comment by BurntSushi** [comment]
> can you provide some documentation

No. This isn't some bespoke X client. It's the result of running [xgbgen](https://github.com/BurntSushi/xgb/tree/deaf085860bc2ec870e50cacc83c467b3501a404/xgbgen) to automatically generate code that implements the X client protocol.

The documentation is therefore the same as what exists for the X client protocol. That's what you need to consult.

For example: https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:GetImage
